# https://github.com/rslgp/docker_compose/blob/main/redis/docker-compose.yml
services:
  redis:
    image: redis:latest
    container_name: my_redis_arbitrio
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data: